// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSUz8j6RDogW0YXMYI0cKAEgKAR9ZulL8',
    appId: '1:543024477084:web:b351bd0c7bf9c5bd34ce59',
    messagingSenderId: '543024477084',
    projectId: 'todo-2d3a4',
    authDomain: 'todo-2d3a4.firebaseapp.com',
    databaseURL: 'https://todo-2d3a4-default-rtdb.firebaseio.com',
    storageBucket: 'todo-2d3a4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2B_keig4PAno5Ai7coC2pUFSkymNRNw4',
    appId: '1:543024477084:android:7aec67548ba1ba9934ce59',
    messagingSenderId: '543024477084',
    projectId: 'todo-2d3a4',
    databaseURL: 'https://todo-2d3a4-default-rtdb.firebaseio.com',
    storageBucket: 'todo-2d3a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-ZoW0r27uO9JlzGwdojP7-m_vs9_F95U',
    appId: '1:543024477084:ios:05141816518058b634ce59',
    messagingSenderId: '543024477084',
    projectId: 'todo-2d3a4',
    databaseURL: 'https://todo-2d3a4-default-rtdb.firebaseio.com',
    storageBucket: 'todo-2d3a4.appspot.com',
    iosBundleId: 'com.example.toDoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-ZoW0r27uO9JlzGwdojP7-m_vs9_F95U',
    appId: '1:543024477084:ios:05141816518058b634ce59',
    messagingSenderId: '543024477084',
    projectId: 'todo-2d3a4',
    databaseURL: 'https://todo-2d3a4-default-rtdb.firebaseio.com',
    storageBucket: 'todo-2d3a4.appspot.com',
    iosBundleId: 'com.example.toDoListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSUz8j6RDogW0YXMYI0cKAEgKAR9ZulL8',
    appId: '1:543024477084:web:28d67263dcd6349134ce59',
    messagingSenderId: '543024477084',
    projectId: 'todo-2d3a4',
    authDomain: 'todo-2d3a4.firebaseapp.com',
    databaseURL: 'https://todo-2d3a4-default-rtdb.firebaseio.com',
    storageBucket: 'todo-2d3a4.appspot.com',
  );

}